### ISSUE TITLE
Dollar sign $ not allowed in values file?

### ISSUE THREAD

**Issue by dev-samples** [unbroken-dome/gradle-helm-plugin#130]
Using version 1.6.1 og the helm plugins for gradle and:

```
helm {
  downloadClient {
    enabled = true
    version = '3.6.2'  
  }

...
}
```

In the default values.yaml file I have:

```
ingress:
  host:
    name: myhost
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /mypath(/|$)(.*)
```

And the corresponding helm template:

```
kind: Ingress
metadata:
  name: hello-app
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host.name }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port }}

```
when I build the corresponding chart with: 

```
./gradlew clean helmPackage -i --stacktrace
```

I get:

```
:helmCollectHelloAppChartDependencies (Thread[Daemon worker,5,main]) completed. Took 0.031 secs.
:helmFilterHelloAppChartSources (Thread[Daemon worker,5,main]) started.

> Task :helmFilterHelloAppChartSources FAILED
Watching 4 directories to track changes
Watching 8 directories to track changes
Caching disabled for task ':helmFilterHelloAppChartSources' because:
  Build cache is disabled
Task ':helmFilterHelloAppChartSources' is not up-to-date because:
  Task has failed previously.
Watching 7 directories to track changes
unknown recognition error type: groovyjarjarantlr4.v4.runtime.LexerNoViableAltException
Watching 11 directories to track changes
:helmFilterHelloAppChartSources (Thread[Daemon worker,5,main]) completed. Took 0.125 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':helmFilterHelloAppChartSources'.
> Could not copy file '/home/user/repos/hello-app/src/helm/hello-app/values.yaml' to '/home/user/repos/hello-app/build/tmp/helm/filtered/hello-app/values.yaml'.
   > java.io.IOException: Stream closed

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':helmFilterHelloAppChartSources'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:188)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:186)

....

        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: Stream closed
        at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:71)
        at org.gradle.api.internal.file.copy.DefaultFileCopyDetails.copyTo(DefaultFileCopyDetails.java:114)
        at org.gradle.api.internal.file.AbstractFileTreeElement.copyFile(AbstractFileTreeElement.java:102)
        at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:83)
        ... 156 more
Caused by: java.io.IOException: Stream closed
        at org.unbrokendome.gradle.pluginutils.io.SimpleTemplateEngineFilterReader$delegate$2.invoke(SimpleTemplateEngineFilterReader.kt:52)
        at org.unbrokendome.gradle.pluginutils.io.SimpleTemplateEngineFilterReader$delegate$2.invoke(SimpleTemplateEngineFilterReader.kt:39)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at org.unbrokendome.gradle.pluginutils.io.SimpleTemplateEngineFilterReader.getDelegate(SimpleTemplateEngineFilterReader.kt)
        at org.unbrokendome.gradle.pluginutils.io.DelegateReader.close(DelegateReader.kt:56)
        at org.apache.commons.io.input.ReaderInputStream.close(ReaderInputStream.java:295)
        at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:68)

```

I works fine if I do a plain `helm package` so having a theory its related to some rules in the helm plugin (SimpleTemplateEngineFilterReader)?

Any ideas?

**UPDATE**

Disabling filtering:
https://unbroken-dome.github.io/projects/gradle-helm-plugin/latest/userguide/index.html#_enable_or_disable_filtering
```
helm {
  filtering.enabled = false
}
```
works for now. So being able to use nginx annotations containing `$` comes with the price of _not_ being able to have filtering enabled it seems?

**Comment by tkrullmann** [comment]
Hi,

the Helm plugin sets the option `escapeBackslash=true` on the template engine exactly for this reason, so you should be able to escape your dollars as `\$` in the filtered files.

**Comment by tkrullmann** [comment]
Updated documentation to clarify the use of backslashes for escaping dollar characters.
