### ISSUE TITLE
:helmLintMainChart'. fails 

### ISSUE THREAD

**Issue by gluehbirnenkopf** [unbroken-dome/gradle-helm-plugin#2]
Hi there,

Actually I face the problem that the task ':helmLintMainChart'. fails all the time. 
I think it is a bug inside your gradle task definition. Or am I wrong here?

Im using version 0.2.1
See stack trace below

> Task :helmLintMainChart FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not evaluate onlyIf predicate for task ':helmLintMainChart'.
> No value has been specified for this provider.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleException: Could not evaluate onlyIf predicate for task ':helmLintMainChart'.
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalStateException: No value has been specified for this provider.
	at org.gradle.api.internal.provider.AbstractProvider.get(AbstractProvider.java:31)
	at org.gradle.api.internal.provider.AbstractMappingProvider.get(AbstractMappingProvider.java:45)
	at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:90)
	at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:90)
	at org.unbrokendome.gradle.plugins.helm.rules.LintTaskRule$apply$2$1$1$1.isSatisfiedBy(LintTaskRule.kt:43)
	at org.unbrokendome.gradle.plugins.helm.rules.LintTaskRule$apply$2$1$1$1.isSatisfiedBy(LintTaskRule.kt:13)
	at org.gradle.api.specs.AndSpec.isSatisfiedBy(AndSpec.java:47)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:42)
	... 20 more

**Comment by gintautassulskus** [comment]
@gluehbirnenkopf, did you find a solution to this issue by any chance?

**Comment by bbxx111** [comment]
@gluehbirnenkopf  I got the same problem. Did you find a solution?

**Comment by tkrullmann** [comment]
Hi, and sorry for the late reply!
I found the problem, it's because the linting can be enabled also by project property `helm.lint.enabled`, if that is missing then there will be no default value leading to the exception above.

**Comment by tkrullmann** [comment]
should be fixed in 0.2.2
