### ISSUE TITLE
Plugin ignores KUBECONFIG environment variable

### ISSUE THREAD

**Issue by travigd** [unbroken-dome/gradle-helm-plugin#60]
Most tools respect this variable, but this plugin does not.

I can work around it by setting it myself, but it seems like this should happen by default.
```kotlin
helm {
    System.getenv("KUBECONFIG")?.let { kubeConfig.set(file(it)) }
}
```

**Comment by Emilio-Pega** [comment]
I am seeing the same, especially on gradle 6.x with 1.2.0 of the plugin.

I think the new worker API logic isn't obeying the  env var.

From the code comments it looks like there was a similar issue with the $HOME envvar 

https://github.com/unbroken-dome/gradle-helm-plugin/blob/master/src/main/kotlin/org/unbrokendome/gradle/plugins/helm/command/HelmExecWorkAction.kt#L35

**Comment by Emilio-Pega** [comment]
While the above work-around function for helmInstall, it fails for helmUninstall with a class cast/serialization error

```
Caused by: org.gradle.api.UncheckedIOException: Unable to store input properties for task ':infrastructure:deployment:sde:sde:helmUninstallDatabaseFromDefault'. Property 'kubeConfig' with value '/home/octopode/admin.conf' cannot be serialized.
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$fingerprintInputProperties$2(CaptureStateBeforeExecutionStep.java:178)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.visitInputProperties(ExecuteActionsTaskExecuter.java:289)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.fingerprintInputProperties(CaptureStateBeforeExecutionStep.java:169)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.captureExecutionState(CaptureStateBeforeExecutionStep.java:149)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$captureExecutionStateOp$1(CaptureStateBeforeExecutionStep.java:104)
```

**Comment by Emilio-Pega** [comment]
Pull request https://github.com/unbroken-dome/gradle-helm-plugin/pull/65

**Comment by tkrullmann** [comment]
Hi, and thanks for the report!

In general, you should _not_ depend on environment variables in Gradle, for several reasons:

(1) when using the Gradle daemon (which is the default), environment variables from the process that started the build (i.e. the shell that runs `gradle` or `./gradlew`) are not always passed to the daemon, it seems to depend heavily on the Gradle version and/or the JDK in use
(2) As a best practice, a build should minimize dependencies on external circumstances. If an environment variable is supposed to influence the build, it is better to pass it to the project with `-Pkey=value` or via gradle.properties.

Therefore the plugin allows `kubeconfig` to be set in various ways, either via the build script or the `helm.kubeConfig` Gradle property.

But I do see your point regarding the conventional use of `KUBECONFIG` with other tools, and it might be what users expect. So I guess it won't hurt to make this one exception.

**Comment by travigd** [comment]
Cheers for pragmatism, and thanks for your time both of you. :)
